import { VirtualizedList } from "react-native";

export const images = {
Vlogo: require('../images/Vlogo.png'),
Logo: require('../images/Logo.png'),
Curve: require('../images/curve.png'),
Car: require('../images/car3.png'),
carPick: require('../images/carPick.png'),
bikePick: require('../images/bikePick.png'),
Facebook: require('../images/Facebook.png'),
Google: require('../images/Googles.png'),
Apple: require('../images/Apple.png'),
VerifyOTP: require('../images/VerifyOtp.png'),
SuccessOTP: require('../images/OTPSucess.png'),
EmailOTP: require('../images/EmailOTP.png'),
EmailSuccess: require('../images/EmailSuccess.png'),
Forgot: require('../images/Forgot.png'),
profileImage: require('../images/Profile.png'),
Path1: require('../images/Path1.png'),
Path2: require('../images/Path2.png'),
Path3: require('../images/Path3.png'),
CarSlider: require('../images/CARSlider.png'),
Scanner: require('../images/scan.png'),
Ride: require('../images/Group8785.png'),
Parking: require('../images/Group8787.png'),
Cleaning: require('../images/Group9719.png'),
User: require('../images/Component.png'),
Business: require('../images/business.png'),
Driver: require('../images/Group87.png'),
wallet: require('../images/wallet.png'),
live: require('../images/Live.png'),
location: require('../images/location.png'),
history: require('../images/HistoryClock.png'),
contactImage: require('../images/contactImage.png'),
success: require('../images/success.png'),
calender: require('../images/calendar.png'),
floor1: require('../images/floor1.png'),
floor2: require('../images/floor2.png'),
floor3: require('../images/floor3.png'),
garage: require('../images/garage.png'),
residence: require('../images/residence.png'),
BookingConfirmationMap: require('../images/BookingConfirmationMap.png'),
applePay: require('../images/applePay.png'),
mastercard: require('../images/mastercard.png'),
visa: require('../images/visa.png'),
waylet: require('../images/waylet.png'),


}