export const images = {
  logo: require('../assets/VeroverLogo.png'),
  profile: require('../assets/ProfileImage.png'),
  wallet: require('../assets/wallet.png'),
  qrcode: require('../assets/qr.png'),
  car: require('../assets/car.png'),
  history: require('../assets/HistoryClock.png'),
  live: require('../assets/Live.png'),
  profileImage: require('../assets/Profile.png'),
  location: require('../assets/location.png'),
  calender: require('../assets/calendar.png'),
  carPick: require('../assets/carPick.png'),
  bikePick: require('../assets/bikePick.png'),
  garage: require('../assets/garage.png'),
  lot: require('../assets/lot.png'),
  residence: require('../assets/residence.png'),
  contactImage: require('../assets/contactImage.png'),
  floor1: require('../assets/floor1.png'),
  floor2: require('../assets/floor2.png'),
  floor3: require('../assets/floor3.png'),
  BookingConfirmationMap: require('../assets/BookingConfirmationMap.png'),
  applePay: require('../assets/applePay.png'),
  mastercard: require('../assets/mastercard.png'),
  visa: require('../assets/visa.png'),
  waylet: require('../assets/waylet.png'),
};
